version: '3'
services:
  server:
    build: ./server
    ports:
      - "65432:65432"
  client1:
    build: ./client
    depends_on:
      - server
    stdin_open: true
    tty: true
  client2:
    build: ./client
    depends_on:
      - server
    stdin_open: true
    tty: true